/*
    Name:       events.h
    Purpose:    Classify wxWindows events
    Author:     David Cuny
    Copyright:  (c) 2002 David Cuny <dcuny@lanset.com>
    Licence:    LGPL

    This file is autogenerated by events.awk from events.i
*/

int wClassifyEvent(WXTYPE eventType);
