/*************************************************************
    Name:       sqlite.c
    Purpose:    include sqlite3 source files
	Author:     David Cuny
    Copyright:  (c) 2006 David Cuny "dcuny@lanset.com"
	Licence:    LGPL
*************************************************************/

//#include "sqlite/btree.h"
//#include "sqlite/hash.h"
//#include "sqlite/keywordhash.h"
//#include "sqlite/opcodes.h"
//#include "sqlite/os_common.h"
//#include "sqlite/os.h"
//#include "sqlite/pager.h"
//#include "sqlite/parse.h"
//#include "sqlite/sqlite3.h"
//#include "sqlite/sqliteInt.h"
//#include "sqlite/vdbe.h"
//#include "sqlite/vdbeInt.h"


#include "sqlite/alter.c"
#include "sqlite/analyze.c"
#include "sqlite/attach.c"
#include "sqlite/auth.c"
#include "sqlite/btree.c"
#include "sqlite/build.c"
#include "sqlite/callback.c"
#include "sqlite/complete.c"
#include "sqlite/date.c"
#include "sqlite/delete.c"
#include "sqlite/expr.c"
#include "sqlite/func.c"
#include "sqlite/hash.c"
#include "sqlite/insert.c"
#include "sqlite/legacy.c"
#include "sqlite/main.c"
#include "sqlite/opcodes.c"
#include "sqlite/os.c"
#include "sqlite/os_unix.c"
#include "sqlite/os_win.c"
#include "sqlite/pager.c"
#include "sqlite/parse.c"
#include "sqlite/pragma.c"
#include "sqlite/prepare.c"
#include "sqlite/printf.c"
#include "sqlite/random.c"
#include "sqlite/select.c"
#include "sqlite/shell.c"
#include "sqlite/table.c"
#include "sqlite/tokenize.c"
#include "sqlite/trigger.c"
#include "sqlite/update.c"
#include "sqlite/utf.c"
#include "sqlite/util.c"
#include "sqlite/vacuum.c"
#include "sqlite/vdbeapi.c"
#include "sqlite/vdbeaux.c"
#include "sqlite/vdbe.c"
#include "sqlite/vdbefifo.c"
#include "sqlite/vdbemem.c"
#include "sqlite/where.c"
