/*************************************************************
    NOTE: THIS FILE IS AUTOGENERATED
    Name:       events.c
    Purpose:    classify wxWindows events
    Author:     David Cuny
    Copyright:  (c) 2003 David Cuny <dcuny@lanset.com>
    Licence:    LGPL
*************************************************************/

/* return pointer to event class */
wSymbol *wClassifyEvent(WXTYPE eventType)
{
    /* wxEvent */
    if (eventType == wxEVT_NC_PAINT) return _wxEvent;
    if (eventType == wxEVT_PALETTE_CHANGED) return _wxEvent;
    if (eventType == wxEVT_CLOSE_WINDOW) return _wxEvent;
    if (eventType == wxEVT_CHAR) return _wxEvent;
    if (eventType == wxEVT_MEASURE_ITEM) return _wxEvent;
    if (eventType == wxEVT_POWER) return _wxEvent;
    if (eventType == wxEVT_COMPARE_ITEM) return _wxEvent;
    if (eventType == wxEVT_QUERY_END_SESSION) return _wxEvent;
    if (eventType == wxEVT_NAVIGATION_KEY) return _wxEvent;
    if (eventType == wxEVT_PAINT_ICON) return _wxEvent;
    if (eventType == wxEVT_SETTING_CHANGED) return _wxEvent;
    if (eventType == wxEVT_MAXIMIZE) return _wxEvent;
    if (eventType == wxEVT_DRAW_ITEM) return _wxEvent;
    if (eventType == wxEVT_CREATE) return _wxEvent;
    if (eventType == wxEVT_SHOW) return _wxEvent;
    if (eventType == wxEVT_MOUSE_CAPTURE_CHANGED) return _wxEvent;
    if (eventType == wxEVT_END_SESSION) return _wxEvent;
    if (eventType == wxEVT_QUERY_NEW_PALETTE) return _wxEvent;
    if (eventType == wxEVT_CONTEXT_MENU) return _wxEvent;
    if (eventType == wxEVT_DESTROY) return _wxEvent;
    if (eventType == wxEVT_SET_CURSOR) return _wxEvent;

    /* wxTimerEvent */
    if (eventType == wxEVT_TIMER) return _wxTimerEvent;

    /* wxCommandEvent */
    if (eventType == wxEVT_COMMAND_RIGHT_DCLICK) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_LISTBOX_DOUBLECLICKED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_LEFT_CLICK) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_SPINCTRL_UPDATED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_VLBOX_SELECTED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_TEXT_UPDATED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_BUTTON_CLICKED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_CHECKLISTBOX_TOGGLED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_RADIOBUTTON_SELECTED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_RIGHT_CLICK) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_LISTBOX_SELECTED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_KILL_FOCUS) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_CHECKBOX_CLICKED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_SET_FOCUS) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_RADIOBOX_SELECTED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_TOOL_ENTER) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_SCROLLBAR_UPDATED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_SLIDER_UPDATED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_TEXT_ENTER) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_COMBOBOX_SELECTED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_CHOICE_SELECTED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_MENU_SELECTED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_TOOL_CLICKED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_ENTER) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_LEFT_DCLICK) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_TOOL_RCLICKED) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_FIND) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_FIND_NEXT) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_FIND_REPLACE) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_FIND_REPLACE_ALL) return _wxCommandEvent;
    if (eventType == wxEVT_COMMAND_FIND_CLOSE) return _wxCommandEvent;

    /* wxActivateEvent */
    if (eventType == wxEVT_ACTIVATE_APP) return _wxActivateEvent;
    if (eventType == wxEVT_ACTIVATE) return _wxActivateEvent;

    /* wxHelpEvent */
    if (eventType == wxEVT_HELP) return _wxHelpEvent;
    if (eventType == wxEVT_DETAILED_HELP) return _wxHelpEvent;

    /* wxCalendarEvent */
    if (eventType == wxEVT_CALENDAR_MONTH_CHANGED) return _wxCalendarEvent;
    if (eventType == wxEVT_CALENDAR_DAY_CHANGED) return _wxCalendarEvent;
    if (eventType == wxEVT_CALENDAR_YEAR_CHANGED) return _wxCalendarEvent;
    if (eventType == wxEVT_CALENDAR_WEEKDAY_CLICKED) return _wxCalendarEvent;
    if (eventType == wxEVT_CALENDAR_DOUBLECLICKED) return _wxCalendarEvent;
    if (eventType == wxEVT_CALENDAR_SEL_CHANGED) return _wxCalendarEvent;

    /* wxIconizeEvent */
    if (eventType == wxEVT_ICONIZE) return _wxIconizeEvent;

    /* wxDropFilesEvent */
    if (eventType == wxEVT_DROP_FILES) return _wxDropFilesEvent;

    /* wxEraseEvent */
    if (eventType == wxEVT_ERASE_BACKGROUND) return _wxEraseEvent;

    /* wxKeyEvent */
    if (eventType == wxEVT_KEY_UP) return _wxKeyEvent;
    if (eventType == wxEVT_KEY_DOWN) return _wxKeyEvent;
    if (eventType == wxEVT_CHAR_HOOK) return _wxKeyEvent;

    /* wxIdleEvent */
    if (eventType == wxEVT_IDLE) return _wxIdleEvent;

    /* wxInitDialogEvent */
    if (eventType == wxEVT_INIT_DIALOG) return _wxInitDialogEvent;

    /* wxListEvent */
    if (eventType == wxEVT_COMMAND_LIST_BEGIN_RDRAG) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_ITEM_MIDDLE_CLICK) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_INSERT_ITEM) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_ITEM_DESELECTED) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_KEY_DOWN) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_DELETE_ALL_ITEMS) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_BEGIN_LABEL_EDIT) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_END_LABEL_EDIT) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_ITEM_SELECTED) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_GET_INFO) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_DELETE_ITEM) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_SET_INFO) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_BEGIN_DRAG) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_ITEM_ACTIVATED) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_COL_CLICK) return _wxListEvent;
    if (eventType == wxEVT_COMMAND_LIST_ITEM_RIGHT_CLICK) return _wxListEvent;

    /* wxMenuEvent */
    if (eventType == wxEVT_MENU_HIGHLIGHT) return _wxMenuEvent;

    /* wxMouseEvent */
    if (eventType == wxEVT_RIGHT_DCLICK) return _wxMouseEvent;
    if (eventType == wxEVT_LEFT_DOWN) return _wxMouseEvent;
    if (eventType == wxEVT_RIGHT_UP) return _wxMouseEvent;
    if (eventType == wxEVT_NC_MIDDLE_UP) return _wxMouseEvent;
    if (eventType == wxEVT_RIGHT_DOWN) return _wxMouseEvent;
    if (eventType == wxEVT_NC_RIGHT_DOWN) return _wxMouseEvent;
    if (eventType == wxEVT_NC_RIGHT_UP) return _wxMouseEvent;
    if (eventType == wxEVT_KILL_FOCUS) return _wxMouseEvent;
    if (eventType == wxEVT_MOTION) return _wxMouseEvent;
    if (eventType == wxEVT_NC_LEFT_DOWN) return _wxMouseEvent;
    if (eventType == wxEVT_NC_MOTION) return _wxMouseEvent;
    if (eventType == wxEVT_NC_LEAVE_WINDOW) return _wxMouseEvent;
    if (eventType == wxEVT_MIDDLE_DOWN) return _wxMouseEvent;
    if (eventType == wxEVT_LEFT_DCLICK) return _wxMouseEvent;
    if (eventType == wxEVT_NC_ENTER_WINDOW) return _wxMouseEvent;
    if (eventType == wxEVT_MIDDLE_UP) return _wxMouseEvent;
    if (eventType == wxEVT_NC_MIDDLE_DOWN) return _wxMouseEvent;
    if (eventType == wxEVT_MIDDLE_DCLICK) return _wxMouseEvent;
    if (eventType == wxEVT_NC_RIGHT_DCLICK) return _wxMouseEvent;
    if (eventType == wxEVT_NC_LEFT_DCLICK) return _wxMouseEvent;
    if (eventType == wxEVT_SET_FOCUS) return _wxMouseEvent;
    if (eventType == wxEVT_LEAVE_WINDOW) return _wxMouseEvent;
    if (eventType == wxEVT_NC_LEFT_UP) return _wxMouseEvent;
    if (eventType == wxEVT_ENTER_WINDOW) return _wxMouseEvent;
    if (eventType == wxEVT_LEFT_UP) return _wxMouseEvent;
    if (eventType == wxEVT_NC_MIDDLE_DCLICK) return _wxMouseEvent;
    if (eventType == wxEVT_MOUSEWHEEL) return _wxMouseEvent;

    /* wxMoveEvent */
    if (eventType == wxEVT_MOVE) return _wxMoveEvent;

    /* wxNotebookEvent */
    if (eventType == wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED) return _wxNotebookEvent;
    if (eventType == wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGING) return _wxNotebookEvent;

    /* wxPaintEvent */
    if (eventType == wxEVT_PAINT) return _wxPaintEvent;

    /* wxProcessEvent */
    if (eventType == wxEVT_END_PROCESS) return _wxProcessEvent;

    /* wxScrollEvent */
    if (eventType == wxEVT_SCROLL_TOP) return _wxScrollEvent;
    if (eventType == wxEVT_SCROLL_THUMBTRACK) return _wxScrollEvent;
    if (eventType == wxEVT_SCROLL_THUMBRELEASE) return _wxScrollEvent;
    if (eventType == wxEVT_SCROLL_LINEUP) return _wxScrollEvent;
    if (eventType == wxEVT_SCROLL_PAGEUP) return _wxScrollEvent;
    if (eventType == wxEVT_SCROLL_PAGEDOWN) return _wxScrollEvent;
    if (eventType == wxEVT_SCROLL_LINEDOWN) return _wxScrollEvent;
    if (eventType == wxEVT_SCROLL_BOTTOM) return _wxScrollEvent;

    /* wxScrollWinEvent */
    if (eventType == wxEVT_SCROLLWIN_TOP) return _wxScrollWinEvent;
    if (eventType == wxEVT_SCROLLWIN_LINEUP) return _wxScrollWinEvent;
    if (eventType == wxEVT_SCROLLWIN_PAGEUP) return _wxScrollWinEvent;
    if (eventType == wxEVT_SCROLLWIN_THUMBRELEASE) return _wxScrollWinEvent;
    if (eventType == wxEVT_SCROLLWIN_BOTTOM) return _wxScrollWinEvent;
    if (eventType == wxEVT_SCROLLWIN_PAGEDOWN) return _wxScrollWinEvent;
    if (eventType == wxEVT_SCROLLWIN_THUMBTRACK) return _wxScrollWinEvent;
    if (eventType == wxEVT_SCROLLWIN_LINEDOWN) return _wxScrollWinEvent;

    /* wxSizeEvent */
    if (eventType == wxEVT_SIZE) return _wxSizeEvent;

    /* wxSocketEvent */
    if (eventType == wxEVT_SOCKET) return _wxSocketEvent;

    /* wxSysColourChangedEvent */
    if (eventType == wxEVT_SYS_COLOUR_CHANGED) return _wxSysColourChangedEvent;

    /* wxTreeEvent */
    if (eventType == wxEVT_COMMAND_TREE_BEGIN_RDRAG) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_KEY_DOWN) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_ITEM_ACTIVATED) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_GET_INFO) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_ITEM_EXPANDING) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_SEL_CHANGED) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_ITEM_COLLAPSED) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_SET_INFO) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_BEGIN_LABEL_EDIT) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_ITEM_EXPANDED) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_SEL_CHANGING) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_ITEM_COLLAPSING) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_BEGIN_DRAG) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_END_DRAG) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_DELETE_ITEM) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_ITEM_MIDDLE_CLICK) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_ITEM_RIGHT_CLICK) return _wxTreeEvent;
    if (eventType == wxEVT_COMMAND_TREE_END_LABEL_EDIT) return _wxTreeEvent;

    /* wxUpdateUIEvent */
    if (eventType == wxEVT_UPDATE_UI) return _wxUpdateUIEvent;

    /* wxWizardEvent */
    if (eventType == wxEVT_WIZARD_PAGE_CHANGED) return _wxWizardEvent;
    if (eventType == wxEVT_WIZARD_PAGE_CHANGING) return _wxWizardEvent;
    if (eventType == wxEVT_WIZARD_CANCEL) return _wxWizardEvent;

    /* wxSplitterEvent */
    if (eventType == wxEVT_COMMAND_SPLITTER_SASH_POS_CHANGING) return _wxSplitterEvent;
    if (eventType == wxEVT_COMMAND_SPLITTER_SASH_POS_CHANGED) return _wxSplitterEvent;
    if (eventType == wxEVT_COMMAND_SPLITTER_DOUBLECLICKED) return _wxSplitterEvent;
    if (eventType == wxEVT_COMMAND_SPLITTER_UNSPLIT) return _wxSplitterEvent;

    /* wxStyledTextEvent */
    if (eventType == wxEVT_STC_CHANGE) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_STYLENEEDED) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_CHARADDED) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_SAVEPOINTREACHED) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_SAVEPOINTLEFT) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_ROMODIFYATTEMPT) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_KEY) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_DOUBLECLICK) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_UPDATEUI) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_MODIFIED) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_MACRORECORD) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_MARGINCLICK) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_NEEDSHOWN) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_POSCHANGED) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_PAINTED) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_USERLISTSELECTION) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_URIDROPPED) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_DWELLSTART) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_DWELLEND) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_START_DRAG) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_DRAG_OVER) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_DO_DROP) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_ZOOM) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_HOTSPOT_CLICK) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_HOTSPOT_DCLICK) return _wxStyledTextEvent;
    if (eventType == wxEVT_STC_CALLTIP_CLICK) return _wxStyledTextEvent;

    /* probably user defined */
    return _wxEvent;
}

WXTYPE wEventNameToType( char *eventName ) {


    /* wxEvent */
    if (strcmp( eventName, "ncpaint") == 0) return wxEVT_NC_PAINT;
    if (strcmp( eventName, "palettechanged") == 0) return wxEVT_PALETTE_CHANGED;
    if (strcmp( eventName, "closewindow") == 0) return wxEVT_CLOSE_WINDOW;
    if (strcmp( eventName, "char") == 0) return wxEVT_CHAR;
    if (strcmp( eventName, "measureitem") == 0) return wxEVT_MEASURE_ITEM;
    if (strcmp( eventName, "power") == 0) return wxEVT_POWER;
    if (strcmp( eventName, "compareitem") == 0) return wxEVT_COMPARE_ITEM;
    if (strcmp( eventName, "queryendsession") == 0) return wxEVT_QUERY_END_SESSION;
    if (strcmp( eventName, "navigationkey") == 0) return wxEVT_NAVIGATION_KEY;
    if (strcmp( eventName, "painticon") == 0) return wxEVT_PAINT_ICON;
    if (strcmp( eventName, "settingchanged") == 0) return wxEVT_SETTING_CHANGED;
    if (strcmp( eventName, "maximize") == 0) return wxEVT_MAXIMIZE;
    if (strcmp( eventName, "drawitem") == 0) return wxEVT_DRAW_ITEM;
    if (strcmp( eventName, "create") == 0) return wxEVT_CREATE;
    if (strcmp( eventName, "show") == 0) return wxEVT_SHOW;
    if (strcmp( eventName, "mousecapturechanged") == 0) return wxEVT_MOUSE_CAPTURE_CHANGED;
    if (strcmp( eventName, "endsession") == 0) return wxEVT_END_SESSION;
    if (strcmp( eventName, "querynewpalette") == 0) return wxEVT_QUERY_NEW_PALETTE;
    if (strcmp( eventName, "contextmenu") == 0) return wxEVT_CONTEXT_MENU;
    if (strcmp( eventName, "destroy") == 0) return wxEVT_DESTROY;
    if (strcmp( eventName, "setcursor") == 0) return wxEVT_SET_CURSOR;

    /* wxTimerEvent */
    if (strcmp( eventName, "timer") == 0) return wxEVT_TIMER;

    /* wxCommandEvent */
    if (strcmp( eventName, "rightdclick") == 0) return wxEVT_COMMAND_RIGHT_DCLICK;
    if (strcmp( eventName, "listboxdoubleclicked") == 0) return wxEVT_COMMAND_LISTBOX_DOUBLECLICKED;
    if (strcmp( eventName, "leftclick") == 0) return wxEVT_COMMAND_LEFT_CLICK;
    if (strcmp( eventName, "spinctrlupdated") == 0) return wxEVT_COMMAND_SPINCTRL_UPDATED;
    if (strcmp( eventName, "vlboxselected") == 0) return wxEVT_COMMAND_VLBOX_SELECTED;
    if (strcmp( eventName, "textupdated") == 0) return wxEVT_COMMAND_TEXT_UPDATED;
    if (strcmp( eventName, "buttonclicked") == 0) return wxEVT_COMMAND_BUTTON_CLICKED;
    if (strcmp( eventName, "checklistboxtoggled") == 0) return wxEVT_COMMAND_CHECKLISTBOX_TOGGLED;
    if (strcmp( eventName, "radiobuttonselected") == 0) return wxEVT_COMMAND_RADIOBUTTON_SELECTED;
    if (strcmp( eventName, "rightclick") == 0) return wxEVT_COMMAND_RIGHT_CLICK;
    if (strcmp( eventName, "listboxselected") == 0) return wxEVT_COMMAND_LISTBOX_SELECTED;
    if (strcmp( eventName, "killfocus") == 0) return wxEVT_COMMAND_KILL_FOCUS;
    if (strcmp( eventName, "checkboxclicked") == 0) return wxEVT_COMMAND_CHECKBOX_CLICKED;
    if (strcmp( eventName, "setfocus") == 0) return wxEVT_COMMAND_SET_FOCUS;
    if (strcmp( eventName, "radioboxselected") == 0) return wxEVT_COMMAND_RADIOBOX_SELECTED;
    if (strcmp( eventName, "toolenter") == 0) return wxEVT_COMMAND_TOOL_ENTER;
    if (strcmp( eventName, "scrollbarupdated") == 0) return wxEVT_COMMAND_SCROLLBAR_UPDATED;
    if (strcmp( eventName, "sliderupdated") == 0) return wxEVT_COMMAND_SLIDER_UPDATED;
    if (strcmp( eventName, "textenter") == 0) return wxEVT_COMMAND_TEXT_ENTER;
    if (strcmp( eventName, "comboboxselected") == 0) return wxEVT_COMMAND_COMBOBOX_SELECTED;
    if (strcmp( eventName, "choiceselected") == 0) return wxEVT_COMMAND_CHOICE_SELECTED;
    if (strcmp( eventName, "menuselected") == 0) return wxEVT_COMMAND_MENU_SELECTED;
    if (strcmp( eventName, "toolclicked") == 0) return wxEVT_COMMAND_TOOL_CLICKED;
    if (strcmp( eventName, "enter") == 0) return wxEVT_COMMAND_ENTER;
    if (strcmp( eventName, "leftdclick") == 0) return wxEVT_COMMAND_LEFT_DCLICK;
    if (strcmp( eventName, "toolrclicked") == 0) return wxEVT_COMMAND_TOOL_RCLICKED;
    if (strcmp( eventName, "find") == 0) return wxEVT_COMMAND_FIND;
    if (strcmp( eventName, "findnext") == 0) return wxEVT_COMMAND_FIND_NEXT;
    if (strcmp( eventName, "findreplace") == 0) return wxEVT_COMMAND_FIND_REPLACE;
    if (strcmp( eventName, "findreplaceall") == 0) return wxEVT_COMMAND_FIND_REPLACE_ALL;
    if (strcmp( eventName, "findclose") == 0) return wxEVT_COMMAND_FIND_CLOSE;

    /* wxActivateEvent */
    if (strcmp( eventName, "activateapp") == 0) return wxEVT_ACTIVATE_APP;
    if (strcmp( eventName, "activate") == 0) return wxEVT_ACTIVATE;

    /* wxHelpEvent */
    if (strcmp( eventName, "help") == 0) return wxEVT_HELP;
    if (strcmp( eventName, "detailedhelp") == 0) return wxEVT_DETAILED_HELP;

    /* wxCalendarEvent */
    if (strcmp( eventName, "calendarmonthchanged") == 0) return wxEVT_CALENDAR_MONTH_CHANGED;
    if (strcmp( eventName, "calendardaychanged") == 0) return wxEVT_CALENDAR_DAY_CHANGED;
    if (strcmp( eventName, "calendaryearchanged") == 0) return wxEVT_CALENDAR_YEAR_CHANGED;
    if (strcmp( eventName, "calendarweekdayclicked") == 0) return wxEVT_CALENDAR_WEEKDAY_CLICKED;
    if (strcmp( eventName, "calendardoubleclicked") == 0) return wxEVT_CALENDAR_DOUBLECLICKED;
    if (strcmp( eventName, "calendarselchanged") == 0) return wxEVT_CALENDAR_SEL_CHANGED;

    /* wxIconizeEvent */
    if (strcmp( eventName, "iconize") == 0) return wxEVT_ICONIZE;

    /* wxDropFilesEvent */
    if (strcmp( eventName, "dropfiles") == 0) return wxEVT_DROP_FILES;

    /* wxEraseEvent */
    if (strcmp( eventName, "erasebackground") == 0) return wxEVT_ERASE_BACKGROUND;

    /* wxKeyEvent */
    if (strcmp( eventName, "keyup") == 0) return wxEVT_KEY_UP;
    if (strcmp( eventName, "keydown") == 0) return wxEVT_KEY_DOWN;
    if (strcmp( eventName, "charhook") == 0) return wxEVT_CHAR_HOOK;

    /* wxIdleEvent */
    if (strcmp( eventName, "idle") == 0) return wxEVT_IDLE;

    /* wxInitDialogEvent */
    if (strcmp( eventName, "initdialog") == 0) return wxEVT_INIT_DIALOG;

    /* wxListEvent */
    if (strcmp( eventName, "listbeginrdrag") == 0) return wxEVT_COMMAND_LIST_BEGIN_RDRAG;
    if (strcmp( eventName, "listitemmiddleclick") == 0) return wxEVT_COMMAND_LIST_ITEM_MIDDLE_CLICK;
    if (strcmp( eventName, "listinsertitem") == 0) return wxEVT_COMMAND_LIST_INSERT_ITEM;
    if (strcmp( eventName, "listitemdeselected") == 0) return wxEVT_COMMAND_LIST_ITEM_DESELECTED;
    if (strcmp( eventName, "listkeydown") == 0) return wxEVT_COMMAND_LIST_KEY_DOWN;
    if (strcmp( eventName, "listdeleteallitems") == 0) return wxEVT_COMMAND_LIST_DELETE_ALL_ITEMS;
    if (strcmp( eventName, "listbeginlabeledit") == 0) return wxEVT_COMMAND_LIST_BEGIN_LABEL_EDIT;
    if (strcmp( eventName, "listendlabeledit") == 0) return wxEVT_COMMAND_LIST_END_LABEL_EDIT;
    if (strcmp( eventName, "listitemselected") == 0) return wxEVT_COMMAND_LIST_ITEM_SELECTED;
    if (strcmp( eventName, "listgetinfo") == 0) return wxEVT_COMMAND_LIST_GET_INFO;
    if (strcmp( eventName, "listdeleteitem") == 0) return wxEVT_COMMAND_LIST_DELETE_ITEM;
    if (strcmp( eventName, "listsetinfo") == 0) return wxEVT_COMMAND_LIST_SET_INFO;
    if (strcmp( eventName, "listbegindrag") == 0) return wxEVT_COMMAND_LIST_BEGIN_DRAG;
    if (strcmp( eventName, "listitemactivated") == 0) return wxEVT_COMMAND_LIST_ITEM_ACTIVATED;
    if (strcmp( eventName, "listcolclick") == 0) return wxEVT_COMMAND_LIST_COL_CLICK;
    if (strcmp( eventName, "listitemrightclick") == 0) return wxEVT_COMMAND_LIST_ITEM_RIGHT_CLICK;

    /* wxMenuEvent */
    if (strcmp( eventName, "menuhighlight") == 0) return wxEVT_MENU_HIGHLIGHT;

    /* wxMouseEvent */
    if (strcmp( eventName, "rightdclick") == 0) return wxEVT_RIGHT_DCLICK;
    if (strcmp( eventName, "leftdown") == 0) return wxEVT_LEFT_DOWN;
    if (strcmp( eventName, "rightup") == 0) return wxEVT_RIGHT_UP;
    if (strcmp( eventName, "ncmiddleup") == 0) return wxEVT_NC_MIDDLE_UP;
    if (strcmp( eventName, "rightdown") == 0) return wxEVT_RIGHT_DOWN;
    if (strcmp( eventName, "ncrightdown") == 0) return wxEVT_NC_RIGHT_DOWN;
    if (strcmp( eventName, "ncrightup") == 0) return wxEVT_NC_RIGHT_UP;
    if (strcmp( eventName, "killfocus") == 0) return wxEVT_KILL_FOCUS;
    if (strcmp( eventName, "motion") == 0) return wxEVT_MOTION;
    if (strcmp( eventName, "ncleftdown") == 0) return wxEVT_NC_LEFT_DOWN;
    if (strcmp( eventName, "ncmotion") == 0) return wxEVT_NC_MOTION;
    if (strcmp( eventName, "ncleavewindow") == 0) return wxEVT_NC_LEAVE_WINDOW;
    if (strcmp( eventName, "middledown") == 0) return wxEVT_MIDDLE_DOWN;
    if (strcmp( eventName, "leftdclick") == 0) return wxEVT_LEFT_DCLICK;
    if (strcmp( eventName, "ncenterwindow") == 0) return wxEVT_NC_ENTER_WINDOW;
    if (strcmp( eventName, "middleup") == 0) return wxEVT_MIDDLE_UP;
    if (strcmp( eventName, "ncmiddledown") == 0) return wxEVT_NC_MIDDLE_DOWN;
    if (strcmp( eventName, "middledclick") == 0) return wxEVT_MIDDLE_DCLICK;
    if (strcmp( eventName, "ncrightdclick") == 0) return wxEVT_NC_RIGHT_DCLICK;
    if (strcmp( eventName, "ncleftdclick") == 0) return wxEVT_NC_LEFT_DCLICK;
    if (strcmp( eventName, "setfocus") == 0) return wxEVT_SET_FOCUS;
    if (strcmp( eventName, "leavewindow") == 0) return wxEVT_LEAVE_WINDOW;
    if (strcmp( eventName, "ncleftup") == 0) return wxEVT_NC_LEFT_UP;
    if (strcmp( eventName, "enterwindow") == 0) return wxEVT_ENTER_WINDOW;
    if (strcmp( eventName, "leftup") == 0) return wxEVT_LEFT_UP;
    if (strcmp( eventName, "ncmiddledclick") == 0) return wxEVT_NC_MIDDLE_DCLICK;
    if (strcmp( eventName, "mousewheel") == 0) return wxEVT_MOUSEWHEEL;

    /* wxMoveEvent */
    if (strcmp( eventName, "move") == 0) return wxEVT_MOVE;

    /* wxNotebookEvent */
    if (strcmp( eventName, "notebookpagechanged") == 0) return wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED;
    if (strcmp( eventName, "notebookpagechanging") == 0) return wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGING;

    /* wxPaintEvent */
    if (strcmp( eventName, "paint") == 0) return wxEVT_PAINT;

    /* wxProcessEvent */
    if (strcmp( eventName, "endprocess") == 0) return wxEVT_END_PROCESS;

    /* wxScrollEvent */
    if (strcmp( eventName, "scrolltop") == 0) return wxEVT_SCROLL_TOP;
    if (strcmp( eventName, "scrollthumbtrack") == 0) return wxEVT_SCROLL_THUMBTRACK;
    if (strcmp( eventName, "scrollthumbrelease") == 0) return wxEVT_SCROLL_THUMBRELEASE;
    if (strcmp( eventName, "scrolllineup") == 0) return wxEVT_SCROLL_LINEUP;
    if (strcmp( eventName, "scrollpageup") == 0) return wxEVT_SCROLL_PAGEUP;
    if (strcmp( eventName, "scrollpagedown") == 0) return wxEVT_SCROLL_PAGEDOWN;
    if (strcmp( eventName, "scrolllinedown") == 0) return wxEVT_SCROLL_LINEDOWN;
    if (strcmp( eventName, "scrollbottom") == 0) return wxEVT_SCROLL_BOTTOM;

    /* wxScrollWinEvent */
    if (strcmp( eventName, "scrollwintop") == 0) return wxEVT_SCROLLWIN_TOP;
    if (strcmp( eventName, "scrollwinlineup") == 0) return wxEVT_SCROLLWIN_LINEUP;
    if (strcmp( eventName, "scrollwinpageup") == 0) return wxEVT_SCROLLWIN_PAGEUP;
    if (strcmp( eventName, "scrollwinthumbrelease") == 0) return wxEVT_SCROLLWIN_THUMBRELEASE;
    if (strcmp( eventName, "scrollwinbottom") == 0) return wxEVT_SCROLLWIN_BOTTOM;
    if (strcmp( eventName, "scrollwinpagedown") == 0) return wxEVT_SCROLLWIN_PAGEDOWN;
    if (strcmp( eventName, "scrollwinthumbtrack") == 0) return wxEVT_SCROLLWIN_THUMBTRACK;
    if (strcmp( eventName, "scrollwinlinedown") == 0) return wxEVT_SCROLLWIN_LINEDOWN;

    /* wxSizeEvent */
    if (strcmp( eventName, "size") == 0) return wxEVT_SIZE;

    /* wxSocketEvent */
    if (strcmp( eventName, "socket") == 0) return wxEVT_SOCKET;

    /* wxSysColourChangedEvent */
    if (strcmp( eventName, "syscolourchanged") == 0) return wxEVT_SYS_COLOUR_CHANGED;

    /* wxTreeEvent */
    if (strcmp( eventName, "treebeginrdrag") == 0) return wxEVT_COMMAND_TREE_BEGIN_RDRAG;
    if (strcmp( eventName, "treekeydown") == 0) return wxEVT_COMMAND_TREE_KEY_DOWN;
    if (strcmp( eventName, "treeitemactivated") == 0) return wxEVT_COMMAND_TREE_ITEM_ACTIVATED;
    if (strcmp( eventName, "treegetinfo") == 0) return wxEVT_COMMAND_TREE_GET_INFO;
    if (strcmp( eventName, "treeitemexpanding") == 0) return wxEVT_COMMAND_TREE_ITEM_EXPANDING;
    if (strcmp( eventName, "treeselchanged") == 0) return wxEVT_COMMAND_TREE_SEL_CHANGED;
    if (strcmp( eventName, "treeitemcollapsed") == 0) return wxEVT_COMMAND_TREE_ITEM_COLLAPSED;
    if (strcmp( eventName, "treesetinfo") == 0) return wxEVT_COMMAND_TREE_SET_INFO;
    if (strcmp( eventName, "treebeginlabeledit") == 0) return wxEVT_COMMAND_TREE_BEGIN_LABEL_EDIT;
    if (strcmp( eventName, "treeitemexpanded") == 0) return wxEVT_COMMAND_TREE_ITEM_EXPANDED;
    if (strcmp( eventName, "treeselchanging") == 0) return wxEVT_COMMAND_TREE_SEL_CHANGING;
    if (strcmp( eventName, "treeitemcollapsing") == 0) return wxEVT_COMMAND_TREE_ITEM_COLLAPSING;
    if (strcmp( eventName, "treebegindrag") == 0) return wxEVT_COMMAND_TREE_BEGIN_DRAG;
    if (strcmp( eventName, "treeenddrag") == 0) return wxEVT_COMMAND_TREE_END_DRAG;
    if (strcmp( eventName, "treedeleteitem") == 0) return wxEVT_COMMAND_TREE_DELETE_ITEM;
    if (strcmp( eventName, "treeitemmiddleclick") == 0) return wxEVT_COMMAND_TREE_ITEM_MIDDLE_CLICK;
    if (strcmp( eventName, "treeitemrightclick") == 0) return wxEVT_COMMAND_TREE_ITEM_RIGHT_CLICK;
    if (strcmp( eventName, "treeendlabeledit") == 0) return wxEVT_COMMAND_TREE_END_LABEL_EDIT;

    /* wxUpdateUIEvent */
    if (strcmp( eventName, "updateui") == 0) return wxEVT_UPDATE_UI;

    /* wxWizardEvent */
    if (strcmp( eventName, "wizardpagechanged") == 0) return wxEVT_WIZARD_PAGE_CHANGED;
    if (strcmp( eventName, "wizardpagechanging") == 0) return wxEVT_WIZARD_PAGE_CHANGING;
    if (strcmp( eventName, "wizardcancel") == 0) return wxEVT_WIZARD_CANCEL;

    /* wxSplitterEvent */
    if (strcmp( eventName, "splittersashposchanging") == 0) return wxEVT_COMMAND_SPLITTER_SASH_POS_CHANGING;
    if (strcmp( eventName, "splittersashposchanged") == 0) return wxEVT_COMMAND_SPLITTER_SASH_POS_CHANGED;
    if (strcmp( eventName, "splitterdoubleclicked") == 0) return wxEVT_COMMAND_SPLITTER_DOUBLECLICKED;
    if (strcmp( eventName, "splitterunsplit") == 0) return wxEVT_COMMAND_SPLITTER_UNSPLIT;

    /* wxStyledTextEvent */
    if (strcmp( eventName, "stcchange") == 0) return wxEVT_STC_CHANGE;
    if (strcmp( eventName, "stcstyleneeded") == 0) return wxEVT_STC_STYLENEEDED;
    if (strcmp( eventName, "stccharadded") == 0) return wxEVT_STC_CHARADDED;
    if (strcmp( eventName, "stcsavepointreached") == 0) return wxEVT_STC_SAVEPOINTREACHED;
    if (strcmp( eventName, "stcsavepointleft") == 0) return wxEVT_STC_SAVEPOINTLEFT;
    if (strcmp( eventName, "stcromodifyattempt") == 0) return wxEVT_STC_ROMODIFYATTEMPT;
    if (strcmp( eventName, "stckey") == 0) return wxEVT_STC_KEY;
    if (strcmp( eventName, "stcdoubleclick") == 0) return wxEVT_STC_DOUBLECLICK;
    if (strcmp( eventName, "stcupdateui") == 0) return wxEVT_STC_UPDATEUI;
    if (strcmp( eventName, "stcmodified") == 0) return wxEVT_STC_MODIFIED;
    if (strcmp( eventName, "stcmacrorecord") == 0) return wxEVT_STC_MACRORECORD;
    if (strcmp( eventName, "stcmarginclick") == 0) return wxEVT_STC_MARGINCLICK;
    if (strcmp( eventName, "stcneedshown") == 0) return wxEVT_STC_NEEDSHOWN;
    if (strcmp( eventName, "stcposchanged") == 0) return wxEVT_STC_POSCHANGED;
    if (strcmp( eventName, "stcpainted") == 0) return wxEVT_STC_PAINTED;
    if (strcmp( eventName, "stcuserlistselection") == 0) return wxEVT_STC_USERLISTSELECTION;
    if (strcmp( eventName, "stcuridropped") == 0) return wxEVT_STC_URIDROPPED;
    if (strcmp( eventName, "stcdwellstart") == 0) return wxEVT_STC_DWELLSTART;
    if (strcmp( eventName, "stcdwellend") == 0) return wxEVT_STC_DWELLEND;
    if (strcmp( eventName, "stcstartdrag") == 0) return wxEVT_STC_START_DRAG;
    if (strcmp( eventName, "stcdragover") == 0) return wxEVT_STC_DRAG_OVER;
    if (strcmp( eventName, "stcdodrop") == 0) return wxEVT_STC_DO_DROP;
    if (strcmp( eventName, "stczoom") == 0) return wxEVT_STC_ZOOM;
    if (strcmp( eventName, "stchotspotclick") == 0) return wxEVT_STC_HOTSPOT_CLICK;
    if (strcmp( eventName, "stchotspotdclick") == 0) return wxEVT_STC_HOTSPOT_DCLICK;
    if (strcmp( eventName, "stccalltipclick") == 0) return wxEVT_STC_CALLTIP_CLICK;

    // throw an error
    wErrorThrow( W_ERROR_SYNTAX,  "Unknown event \"%s\"", eventName );

}
