#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds sample for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=wxbasic
OBJECTS = $(TARGET).obj
EXTRALIBS=$(WXDIR)\lib\stc.lib

!include $(WXDIR)\src\makeprog.b32

